name: tt
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
  intl: ^0.15.7
  flutter_gallery_assets: ^0.1.6
  image_picker: 
  sqljocky5: ^2.2.1
  fluttertoast: ^2.1.0
  page_view_indicator: ^0.3.0+1
  carousel_slider: ^1.3.1
  expandable: ^3.0.0+1
  firebase_auth: '0.7.0'
  firebase_database: '1.0.5'
  firebase_storage: '1.0.4'
  google_sign_in: '3.2.4'
  flutter_speed_dial: ^1.2.1
  toast:
  avatar_glow:
  folding_cell: ^0.1.2
  flutter_rating: ^0.0.2
  rflutter_alert: ^1.0.3
  fancy_dialog: ^1.0.3
  flippo_navigation: ^0.0.6
  drawerbehavior: ^0.0.8
  fancy_bottom_bar: ^0.0.1
  eva_icons_flutter: ^2.0.0
  dropdownfield: ^1.0.3
  flutter_signin_button: ^1.0.0
  carousel_pro: ^1.0.0
  circular_profile_avatar: ^1.0.3
  chip_list_choice: ^0.0.5
  material_design_icons_flutter: ^3.4.4795
  url_launcher:
  syncfusion_flutter_charts: ^17.4.46
  # easy_web_view: ^1.0.1
  # webview_flutter:
  





  cupertino_icons: ^0.1.2
  http: any

dev_dependencies:
  json_serializable: ^2.0.0
  build_runner: ^1.1.2
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
        - assets/images/
#        -images/Hospitality-Travel.png
#        -images/1.png
#        -images/2.png
#        -images/3.png
#        -images/4.png
#        -images/5.png


